export enum DisplayEnum {
  XSMALL = 'XSmall',
  SMALL = 'Small',
  MEDIUM = 'Medium',
  LARGE = 'Large',
  XLARGE = 'XLarge',
  HANDSET = 'Handset',
  TABLET = 'Tablet',
  WEB = 'Web',
  HANDSET_PORTRAIT = 'HandsetPortrait',
  TABLET_PORTRAIT = 'TabletPortrait',
  WEB_PORTRAIT = 'WebPortrait',
  HANDSET_LANDSCAPE = 'HandsetLandscape',
  TABLET_LANDSCAPE = 'TabletLandscape',
  WEB_LANDSCAPE = 'WebLandscape',
}
